---
openapi: 3.0.1
info:
  title: 효순이들
  description: 효림의료재단 AI기반 파킨슨병 스마트 돌봄 시스템 API 문서
  version: '1.0'
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  "/api/v1/test/hello":
    get:
      tags:
      - test-controller
      operationId: test
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                type: object
components: {}
